<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xmlns:py="http://genshi.edgewall.org/">
  <xi:include href="site.html"/>

  <?python
    import traceback
    from mercurial.hgweb import common

    debug = req.web.configbool('hgsite', 'debug', False)
  ?>
  <head>
    <title>${meta.project} &ndash; ${meta.description}</title>
  </head>

  <body py:with="typ, value, tb = exc_info; is_error = isinstance(value, common.ErrorResponse)">
    <div id="content">
      <h2>Oops, that's an error...</h2>
      <py:choose>
        <py:when test="is_error">
          <p>${value}</p>
        </py:when>
        <py:otherwise>
          <p>Something went wrong while processing your request.</p>
          <py:choose>
            <highlight py:when="debug" lexer="pytb">${''.join(traceback.format_exception(typ, value, tb))}</highlight>
            <pre py:otherwise="">${value}</pre>
          </py:choose>
        </py:otherwise>
      </py:choose>
    </div>
  </body>
</html>
